name: taskline
description: Manage your tasks with a single line.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

  package_info_plus: ^1.4.3+1

  flutter_riverpod: ^1.0.4

  dynamic_colorscheme: ^1.0.1

  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  analyzer: ^4.6.0
  dart_code_metrics: ^4.18.0-dev.2

flutter:
  uses-material-design: true
