name: taskline
description: Manage your tasks with a single line.

publish_to: "none"

version: 0.2.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

  package_info_plus: ^1.4.3+1

  flutter_riverpod: ^1.0.4

  dynamic_color: ^1.5.4

  url_launcher: ^6.1.5
  intl: ^0.17.0

  bubble_tab_indicator: ^0.1.6

  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  analyzer: ^4.6.0
  dart_code_metrics: ^4.18.0-dev.2

  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
